# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace # trims trailing whitespace
    -   id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
    -   id: mixed-line-ending # replaces or checks mixed line ending
    -   id: check-symlinks # checks for symlinks which do not point to anything
    -   id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
    # Git
    -   id: check-merge-conflict # checks for files that contain merge conflict strings
    # Python
    -   id: check-docstring-first # checks a common error of defining a docstring after code
    -   id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        name: black
        args: ['--config=./light-curve/pyproject.toml', './light-curve']
-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        args: ['--profile=black', '--filter-files']
-   repo: local
    hooks:
    -   id: cargo-fmt
        name: cargo fmt
        language: rust
        entry: cargo --manifest-path=light-curve/Cargo.toml
        files: \.rs
    -   id: cargo-clippy-fix
        name: cargo clippy fix
        language: rust
        entry: cargo --manifest-path=light-curve/Cargo.toml --all-targets --fix
        files: \.rs
    -   id: cargo-clippy-check
        name: cargo clippy check
        language: rust
        entry: cargo --manifest-path=light-curve/Cargo.toml --all-targets -- -D warnings
        files: \.rs

# pre-commit.ci settings
# Skip clippy, because it fails to download dependencies
ci:
    skip: [cargo-clippy-fix, cargo-clippy-check]
