name: Publish Python packages

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  cibuildwheel:
    name: Build ${{ matrix.platform }} ${{ matrix.arch }} ${{ matrix.interpreter }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ./light-curve

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-11]
        arch: [aarch64, ppc64le, x86_64]
        interpreter: [cp37, cp38, cp39, cp310, cp311, pp37, pp38, pp39]
        platform: [manylinux, musllinux, macosx]
        exclude:
          # Build Linux on Linux
          - os: macos-11
            platform: manylinux
          - os: macos-11
            platform: musllinux
          # Build macOS on macOS
          - os: ubuntu-20.04
            platform: macosx
          # PyPy doesn't support musllinux
          - interpreter: pp37
            platform: musllinux
          - interpreter: pp38
            platform: musllinux
          - interpreter: pp39
            platform: musllinux
          # PyPy doesn't support PPC64le
          - arch: ppc64le
            interpreter: pp37
          - arch: ppc64le
            interpreter: pp38
          - arch: ppc64le
            interpreter: pp39
          # There is no Rust toolchain for PPC64le with MUSL
          - arch: ppc64le
            platform: musllinux
          # x86_64 is the only supported architecture for macOS
          - os: macos-11
            arch: aarch64
          - os: macos-11
            arch: ppc64le

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: ${{ matrix.os != 'macos-11' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set CIBW_BUILD
        run: echo "CIBW_BUILD=${{ matrix.interpreter }}-${{ matrix.platform }}_${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Set CIBW_ARCHS
        run: echo "CIBW_ARCHS=${{ matrix.arch }}" >> $GITHUB_ENV

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        with:
          package-dir: ./light-curve
        env:
          CIBW_BUILD_VERBOSITY: "3"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          if-no-files-found: error

  sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./light-curve

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install maturin
        run: pip install 'maturin>=0.14,<0.15'

      - name: Build sdist
        run: maturin sdist

      - name: Upload sdist as an artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./light-curve/target/wheels/*.tar.gz
          if-no-files-found: error

  publish:
    needs: [cibuildwheel, sdist]

    name: Publish light-curve
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/download-artifact@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install twine
        run: pip install twine

      - name: Publish light-curve
        working-directory: artifact
        run: twine upload *whl *tar.gz -u __token__ -p ${{ secrets.PYPI_TOKEN_LIGHT_CURVE }} --verbose

  publish-light-curve-python:
    needs: publish

    name: Publish light-curve-python
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: light-curve-python

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: python3 -mpip install toml twine

      - name: Publish light-curve-python
        run: |
          python3 setup.py sdist
          twine check --strict dist/*
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN_LIGHT_CURVE_PYTHON }} --verbose
