name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  py_build_deps:
    outputs:
      output: ${{ steps.extract_from_toml.outputs.output }}

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: light-curve

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Extract build deps from pyproject.toml
      id: extract_from_toml
      run: |
        echo "output="$(python -c 'import tomllib; print(" ".join(tomllib.load(open("pyproject.toml", "rb"))["build-system"]["requires"]))') >> "$GITHUB_OUTPUT"


  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python_minor: ['8', '9', '10', '11', '12']

    defaults:
      run:
        working-directory: light-curve

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Python 3.${{ matrix.python_minor }}
      uses: actions/setup-python@v5
      with:
        python-version: "3.${{ matrix.python_minor }}"
    - name: Install tox
      run: pip install tox
    - name: Run Python tests
      run: tox -e py3${{ matrix.python_minor }}

  cargo-fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo fmt --manifest-path=light-curve/Cargo.toml -- --check

  cargo-clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "stable-${{ runner.os }}"
        workspaces: "light-curve"
    - run: cargo clippy --manifest-path=light-curve/Cargo.toml --all-targets -- -D warnings

  coverage:
    runs-on: ubuntu-latest

    needs: [py_build_deps]

    defaults:
      run:
        working-directory: light-curve

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "stable-${{ runner.os }}"
          workspaces: "light-curve"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install build deps
        run: pip install "${{ needs.py_build_deps.outputs.output }}"
      - name: Generate code coverage
        run: |
          source <(cargo llvm-cov show-env --export-prefix)
          python -m venv venv
          source venv/bin/activate
          maturin develop --extras=test-no-bench,test
          python -m pytest
          cargo llvm-cov report --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  benchmarks:
    runs-on: ubuntu-latest

    needs: [py_build_deps]

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libfftw3-dev libgsl-dev
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            cd light-curve
            python3 -m venv venv
            . venv/bin/activate
            pip install "${{ needs.py_build_deps.outputs.output }}" pytest-codspeed
            maturin develop --extras=test-no-bench,test --release --no-default-features --features=ceres-source,fftw-system,gsl,mimalloc
            python3 -mpytest -m "not (nobs or multi)" --codspeed tests/test_w_bench.py

  msrv-build:
    runs-on: ubuntu-latest

    needs: [py_build_deps]

    defaults:
      run:
        working-directory: light-curve

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Get minimum supported Rust version
      run: echo "::set-output name=msrv::$(grep '^rust-version = ' Cargo.toml | grep -o '[0-9.]\+')"
      id: get_msrv
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ steps.get_msrv.outputs.msrv }}
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "msrv-${{ runner.os }}"
        workspaces: "light-curve"
    - name: Install build_deps
      run: pip install "${{ needs.py_build_deps.outputs.output }}"
    - name: Build
      run: |
        rustup default ${{ steps.get_msrv.outputs.msrv }}
        maturin build --find-interpreter

  arm:
    runs-on: [self-hosted, linux, ARM64]

    needs: [py_build_deps]

    defaults:
      run:
        working-directory: light-curve

    steps:
    - uses: actions/checkout@v4
    - name: Install build_deps
      run: pip install "${{ needs.py_build_deps.outputs.output }}"
    - name: Build
      run: maturin build
